use_frameworks!

target 'WSDatePicker_Example' do
  pod 'WSDatePicker', :path => '../'

  target 'WSDatePicker_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
